DEFRA/pafs_core

app/views/pafs_core/projects/steps/_funding_calculator_upload.html.erb, app/views/summary/_data_notice.html.erb, config/locales/steps.en.yml
PM-752,PM-751,PM-770: all text changes.
Plus corrected aria_controls attribute that I had left set incorrectly in the _funding_calculator_upload.html.erb new details tag (if not corrected I guess it may have confused a screen reader or something).
=> PM-752,PM-751,PM-770

app/controllers/pafs_core/application_controller.rb, lib/pafs_core.rb, lib/pafs_core/custom_headers.rb, spec/lib/pafs_core/custom_headers_spec.rb, spec/spec_helper.rb
https://eaflood.atlassian.net/browse/PM-286
Following a PEN test it was flagged that the service has not specified a [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) in the response headers sent back from the app to the clients browser.
For reference CSP
> [..] is an HTTP response header that restricts the browser to loading external assets such as scripts, styles or media from a wide variety of sources — as well as inline scripts. It is intended to prevent wide categories of attacks, such as cross-site scripting (XSS), click-jacking and other forms of code injection.
>
> *https://blog.sqreen.io/integrating-content-security-policy-into-your-rails-applications-4f883eed8f45/*
Prior to this change we had logic that set custom headers via a `before_filter` in …
=> Add CSP to response headers

Gemfile.lock, app/controllers/pafs_core/application_controller.rb, config/initializers/secure_headers.rb, lib/pafs_core/custom_headers.rb, pafs_core.gemspec, spec/controllers/pafs_core/application_controller_spec.rb, spec/dummy/config.ru, spec/lib/pafs_core/custom_headers_spec.rb
https://eaflood.atlassian.net/browse/PM-286
PR #128 was part of adding a Content-Security-Policy to the response header for all responses. However it was spotted that the layout in the **pafs-user** app has a section related to Google Analytics which is only added if the env var `GOOGLE_ANALYTICS_ID` is present.
We therefore need to update the policy to include these sources from Google, as `GOOGLE_ANALYTICS_ID` will be present in the production environment.
=> Add google analytics content 2 Content Sec. Policy

app/views/pafs_core/projects/confirm_area.html.erb, app/views/pafs_core/projects/confirm_rma.html.erb
The links in the confirm pages (essentially the done pages for PAFS) were set to just point back on themselves. This change updates the links to point to the services GDS feedback page, pulling the value from config and ensuring the page opens in a new tab.
=> Update links in confirm pages to use real links

app/models/pafs_core/project.rb, lib/pafs_core/rfcc_codes.rb, spec/services/pafs_core/project_service_spec.rb
https://eaflood.atlassian.net/browse/PM-151
As part of finalising the areas.csv file which will be used to seed the database (see https://github.com/DEFRA/pafs-user/pull/116) we added in some test areas. This will allow the team to investigate issues, or demonstrate functionality without adding dummy data to real areas.
However we had not considered that we have RFCC codes which are used to determine the project reference number, that did not recognise these new test areas.
This change fixes that by adding a new RFC code (TS) which projects linked to test areas will use, and ensuring an validation will work with the new RFCC code.
=> Update RFCC codes to include test areas

.overcommit.yml, .overcommit_gems.rb.lock, app/decorators/pafs_core/imported_project_decorator.rb, app/models/pafs_core/project.rb, app/presenters/pafs_core/spreadsheet_presenter.rb, app/services/pafs_core/program_upload_service.rb, db/migrate/20170328091527_add_consented_flag_to_project.rb, spec/dummy/db/schema.rb
Added consented flag to PafsCore::Project and updated decorator and presented to use this value.
This enables us to indicate whether a proposal has been consented for funding in the annual programme refresh.
=> Added consented flag to project

app/presenters/pafs_core/spreadsheet_presenter.rb
Fixes issue where if the financial year the project will last spend funds is brought in (e.g. from 2032 to 2025) and figures had been entered for the flood and coastal protection values later than the new date, these values were still exported in the FCERM1 spreadsheet.
=> Fixed issue with outputting OM2/3 values (PM-48)

app/assets/stylesheets/pafs_core/_projects.scss, app/controllers/pafs_core/downloads_controller.rb, app/controllers/pafs_core/projects_controller.rb, app/helpers/pafs_core/projects_helper.rb, app/jobs/pafs_core/asite_submission_job.rb, app/models/pafs_core/state.rb, app/presenters/pafs_core/projects_download_presenter.rb, app/services/pafs_core/asite_service.rb, app/services/pafs_core/project_navigator.rb, app/services/pafs_core/project_service.rb, app/services/pafs_core/spreadsheet_service.rb, app/views/pafs_core/downloads/all.html.erb, app/views/pafs_core/downloads/index.html.erb, app/views/pafs_core/projects/index.html.erb, app/views/pafs_core/projects/show.html.erb, config/routes.rb, lib/pafs_core/files.rb, spec/factories/users.rb, spec/services/pafs_core/project_service_spec.rb, spec/services/pafs_core/spreadsheet_service_spec.rb
https://eaflood.atlassian.net/browse/PM-297
This is the first step in offering users the ability to export all projects with a given status into a FCERM1 csv or spreadsheet. This change focuses on the back end, and expanding the exist functionality to
- search for all projects matching a given status for a user
- depending on user type this could encompass multiple areas
- export those projects into a csv or xlsx file using the FCERM1 format
Users of the service have expressed that they still wish to be able to work with project data in spreadsheets as they currently do, but currently the functionality in the system only allows for the export of one project per file.
The functionality this change will add will be linked to changes in the UI in the future, that will allow users to access …
=> Add ability 2 generate file with multiple projects

app/services/pafs_core/program_upload_service.rb, db/migrate/20170424093915_add_reset_consented_flag_to_program_upload.rb, spec/dummy/db/schema.rb
Added ability to import partial programme import or data fixes through the programme refresh spreadsheet import.  This is to facilitate fixes to the project area, for example, without requiring console access and a dev.
=> Added reset consented flag to programme import

app/controllers/pafs_core/projects_controller.rb, app/jobs/pafs_core/account_request_cleanup_job.rb, app/jobs/pafs_core/asite_submission_job.rb, app/jobs/pafs_core/generate_area_programme_job.rb, app/jobs/pafs_core/import_program_refresh_job.rb, app/services/pafs_core/area_download_service.rb
Issue reported where background jobs experience failures obtaining db connections, so wrapping the job code with `ActiveRecord::Base.connection_pool.with_connection` blocks to ensure they get and return a connection to the pool.
=> Wrapped jobs with AR connection pool block

app/steps/pafs_core/funding_calculator_step.rb, spec/factories/steps.rb, spec/steps/pafs_core/funding_calculator_step_spec.rb
Resolves the issue of users uploading outdated PF Calculators.
We now check the calculator version, after we've done a virus check, to make sure that the user has the latest version.
If they do not, we return false and display an error message.
https://eaflood.atlassian.net/browse/PK-962
=> [PK-962] validate Partnership Funding Calculator

app/steps/pafs_core/other_ea_contributors_step.rb, config/locales/steps.en.yml, spec/steps/pafs_core/other_ea_contributors_step_spec.rb
Update copy to include the word 'expected' when determining the expected contributions from other EA functions or sources.
=> [PK-910] - 'Expected' Environment Agency sources

.travis.yml, app/steps/pafs_core/coastal_erosion_protection_outcomes_step.rb, app/steps/pafs_core/flood_protection_outcomes_step.rb, app/views/pafs_core/projects/steps/coastal_erosion_protection_outcomes.html.erb, app/views/pafs_core/projects/steps/flood_protection_outcomes.html.erb, config/locales/steps.en.yml, db/migrate/20180529124243_add_reduced_households_for_floods_and_coastal_erosion.rb
Allow users to select whether their project moves any households into lower flood and coastal erosion risk.
=> [PK-931] Amend service validation to allow projects that don't protect households

app/presenters/pafs_core/validation_presenter.rb
The project validation should not be triggered when a project does not have any households that are protected from floods and coastal erosion
=> [PK-931] - Amend service validation

app/views/pafs_core/projects/index.html.erb
Remove sort filters from the project name and created at columns on the projects page.
=> [PK-1026] Remove the filter/sort arrows from the list of projects table

app/services/pafs_core/project_navigator.rb, app/services/pafs_core/project_service.rb
Allow users to download of proposals regardless of the project state
=> [PK-970] Area programming staff download 'draft' status projects

app/presenters/pafs_core/spreadsheet_presenter.rb
Discovered a bug where by proposals without dates throw an exception when generating the area programme,.
=> Don't assume that we have proposal dates set

Gemfile.lock, lib/pafs_core/engine.rb, spec/factories/account_requests.rb
As part of https://eaflood.atlassian.net/browse/PK-1082 we are required to expose an API via `pafs-users`.
To achieve this we'll be re-using the factories supplied in this gem to setup the necessary test data.
=> Update Engine to re-use factories

spec/controllers/pafs_core/projects_controller_spec.rb, spec/factories/steps.rb
Changes include using the current year as the financial year end,
meaning that we won't have to keep changing this in the future.
=> Fix tests that now break as we're in a new tax year.

app/models/pafs_core/state.rb, spec/controllers/pafs_core/projects_controller_spec.rb, spec/factories/projects.rb, spec/factories/state.rb
Adds a new factory for the project state and extracts the valid states
to a constant to allow reuse of the valid states.
=> [PM-384] Refactor project state and add factory

app/models/pafs_core/project.rb, lib/pafs_core.rb, lib/pafs_core/data_migration/remove_duplicate_states.rb, lib/tasks/pafs_core_tasks.rake, spec/lib/pafs_core/data_migration/remove_duplicate_states_spec.rb
* Rake task and service object to remove spurious state objects from projects
* Race condition when updating the project state can cause multiple state objects to be created for the same project.
* These duplicate states are affecting a join used to generate reports on the data, leading to duplicated rows.
=> [PM-366] Fix data duplication on state change

app/presenters/pafs_core/spreadsheet_presenter.rb, config/locales/spreadsheet.en.yml, spec/presenters/pafs_core/spreadsheet_presenter_spec.rb
When a non-urgent project is rendered, the JSON should use 'Not Urgent'
ad the moderation code
=> [PM-404] Mod code should be 'Not Urgent' in JSON

app/views/pafs_core/projects/index.html.erb
* Replaces the create project button with wording to refer PSO users to PoL
to create Projects.
=> [PM-436] Add wording to refer PSO's to PoL

app/views/pafs_core/projects/_submit_project.html.erb
* No longer need instructions for ensuring that all info is entered when
the PSO user cannot submit the project
=> [PM-377] Remove spurious header

app/helpers/pafs_core/projects_helper.rb
* Need to make the creation independent from the other changes to PSO
permissions.
* Moved from FORCE_PSO_TO_POL to PSO_CANNOT_CREATE_PROJECTS
* Defaults to 'false' i.e. with the flag not set, we allow PSOs to
create projects
=> [PM-436] Move proposal creation to new env var

Gemfile, app/controllers/pafs_core/projects_controller.rb, app/jobs/pafs_core/pol/submission_job.rb, lib/pafs_core.rb, lib/pafs_core/pol/submission.rb, spec/lib/pafs_core/pol/submission_spec.rb
* Add a class to submit a project to Pol
* Requires two environment variables to be set:
- POL_SUBMISSION_URL
This is the url of the endpoint that receives the submission. This needs to be set in order to activate the submission to PoL. Without this, submission behaves as before.
- AZURE_VAULT_AUTH_TOKEN_KEY_NAME_SUBMISSION
This is the name of the key in Azure Vault that holds the
authentication token for PoL to accept the request
=> [PM-357] Submitting a project sends it to PoL

app/models/pafs_core/project.rb, spec/factories/projects.rb
Adds a scope to the project that allows us to restrict to submitted projects. Also adds a couple of traits to allow testing of the project submission to PoL
=> [PM-451] Add submitted to pol scope

app/helpers/pafs_core/projects_helper.rb, app/views/pafs_core/projects/_submit_project.html.erb
* Reverting to draft is only possible via PoL once we turn on the force
to pol flag
* Editing projects should be restricted to non-submitted projects, and
only for rma projects or psos once the force-to-pol flag is false
=> [PM-526] Remove revert to draft button and fix edit capabilities

lib/pafs_core/mapper/partnership_funding_calculator.rb, spec/lib/pafs_core/mapper/partnership_funding_calculator_spec.rb
Looks like a typo. Fixed as requested by PF
=> [PM-539] Change `long_time_loss` to `long_term_loss`

app/decorators/pafs_core/imported_project_decorator.rb, app/services/pafs_core/projects/status_update.rb, spec/services/pafs_core/projects/status_update_spec.rb
* FCERM import would previously not correctly coerce the project status
* This lead to the status always being set to draft
* This fix correctly coerces the values from the status filed and
assigns the correct state.
=> [PM-546] Allow imports to specify the project status

.travis.yml, Gemfile.lock
Build was failing when attempting to use a version of bundler that was
not installed. This PR updates the travis.yml to add a before_install
step that pins bundler at the correct version.
It also adds an optimisation to only clone in travis to a depth of 3 as
opposed to 50.
=> [NO-JIRA] Fix bundler version used by travis

app/presenters/pafs_core/partnership_funding_calculator_presenter.rb, lib/pafs_core/mapper/partnership_funding_calculator.rb
This allows PoL to process the output JSON in the case that the project
being serialized does not have a PFC by adding default, null values to
the output, and preserving the structure.
=> [PM-568] Add defaults to PFC mapper

app/assets/javascripts/pafs_core/funding_contributors.js
When generating the HTML for adding a new contributor, the JS was not
updating the ID. THis updates the ID to use a new value on subsequent
new contributors
=> [PM-585] Fix duplicate ids when adding funding contributors

app/services/pafs_core/development_file_storage_service.rb, app/services/pafs_core/download/meta.rb, lib/pafs_core/files.rb
When generating a new FCRM1, the upload portion reads the file into
memory and causes a spike in memory usage. This can be significant
enough to crash the server due to OOM errors.
Rather than read the file into memory, it should be streamed to s3. No
functionality should change when generating or downloading FCRM1 or
related files.
=> [PM-612] Reduce memory usage when uploading to S3

app/helpers/pafs_core/projects_helper.rb, app/views/pafs_core/projects/_submit_project.html.erb
When submitting a project as an RMA, we need to allow the business to
switch the confirmation of a project by a PSO off.
New env var SKIP_PSO_CONFIRMATION handles this option.
=> [PM-613] Add switch to skip PSO confirmation on submit

app/views/summary/_natural_flood_risk_measures.html.erb, config/locales/en.yml, config/locales/summary.en.yml
https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-1920
Adds "Not provided" to summary section for natural flood risk measures when a user has not provided an answer. Also moves text into the translations files.
=> update nfm summary section

app/presenters/pafs_core/camc3_presenter.rb, app/presenters/pafs_core/spreadsheet_presenter.rb, spec/presenters/pafs_core/camc3_presenter_spec.rb
https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-1974
This is an old FCERM1 requirement that is no longer needed for AIMS PD
Prior to its removal, it summed up all properties protected past 2026 in each year past 2026.
Also changes the financial years the cam3cpresenter to go up to the projects' financial year end rather than the arbitrary fixed value of 2028.
=> Remove 2026 maximum for om figures

app/controllers/pafs_core/archives_controller.rb, app/controllers/pafs_core/areas_controller.rb, app/controllers/pafs_core/bootstraps_controller.rb, app/controllers/pafs_core/downloads_controller.rb, app/controllers/pafs_core/errors_controller.rb, app/controllers/pafs_core/multi_downloads_controller.rb, app/controllers/pafs_core/pages_controller.rb, spec/services/pafs_core/calculator_parser_spec.rb
This change disambiguates inheritance from `ApplicationController`, ensuring that `PafsCore` controllers inherit from `PafsCore::ApplicationController` and no other `ApplicationController` class.
https://eaflood.atlassian.net/browse/RUBY-2108
=> Specify PafsCore namespace for ApplicationController inheritance

Gemfile.lock, app/views/pafs_core/projects/show.html.erb
This fixes a bug where a form object instead of a "project" prefix was being passed to the `form_group` helper.
https://eaflood.atlassian.net/browse/RUBY-2178
=> Fix form-group id error

app/assets/stylesheets/pafs_core/_projects.scss, app/views/pafs_core/summary/_coastal_erosion_protection_outcomes_detail.html.erb, app/views/pafs_core/summary/_flood_protection_outcomes_detail.html.erb, app/views/pafs_core/summary/_funding_sources_and_spending_detail.html.erb, app/views/pafs_core/summary/_natural_flood_risk_measures.html.erb
This change drops the grey background from contributor values tables and cleans up the stylesheets. It also fixes a missing translation error and an issue with some page titles stacking up.
https://eaflood.atlassian.net/browse/RUBY-2178
=> Layout fixes

app/assets/stylesheets/pafs_core/_projects.scss, app/views/pafs_core/projects/index.html.erb
This fixes the HTML structure for the projects view so that the search bar is not missing for non-RMA users.
https://eaflood.atlassian.net/browse/RUBY-2310
=> Fix project search HTML

app/services/pafs_core/area_download_service.rb, spec/services/pafs_core/area_download_service_spec.rb
This changes the rules for starting an area download generation job. Previously, submission was prevented if the status was "generating", in order to prevent duplicate jobs. However this caused issues in some cases where the previous generation job had failed and the status was stuck at "generating". This change allows job submission regardless of the current state.
https://eaflood.atlassian.net/browse/RUBY-2409
=> Always allow area download generation

app/presenters/pafs_core/moderation_presenter.rb, app/services/pafs_core/area_download_service.rb, app/views/pafs_core/multi_downloads/_generating.html.erb, app/views/pafs_core/projects/downloads/moderation.txt.erb, lib/pafs_core/configuration.rb, spec/factories/projects.rb, spec/presenters/pafs_core/moderation_presenter_spec.rb
Some projects in production do not have an owning area and this trips up the `moderation_presenter`. This change allows the presenter to show blank values, while also logging an error to Errbit with the project's reference number so that these projects can be flagged for corrective action.
https://eaflood.atlassian.net/browse/RUBY-2388
=> Handle missing owner in moderation presenter

app/services/pafs_core/download/all.rb, spec/services/pafs_core/download/all_spec.rb
https://eaflood.atlassian.net/browse/RUBY-2599
- Archived projects should be excluded from FCRM1 report
=> RUBY-2599: excluding archived projects from fcrm download

spec/factories/areas.rb
fixing :rma_area factory to create a correct parent object
=> Fixing area factory

app/steps/pafs_core/earliest_start_date_with_gia_step.rb, spec/steps/pafs_core/earliest_start_date_with_gia_step_spec.rb
Validation on date field - 'What is the earliest date the project could start if Grant in Aid funding was made available earlier?'
https://eaflood.atlassian.net/browse/RUBY-2590
=> [RUBY-2590] adding date validation for earliest_start_date_with_gia step

app/presenters/pafs_core/camc3_presenter.rb, spec/factories/projects.rb, spec/presenters/pafs_core/camc3_presenter_spec.rb
https://eaflood.atlassian.net/browse/RUBY-2593
Fixing bug with risk values being exported to JSON even when no risk category is selected
=> [RUBY-2593] zeroing risk values for Camc3Presenter when no risks selected

app/views/pafs_core/summary/_flood_protection_outcomes2040_detail.html.erb, app/views/pafs_core/summary/_flood_protection_outcomes_detail.html.erb, app/views/pafs_core/summary/_risks.html.erb
Added missing column to flooding table
https://eaflood.atlassian.net/browse/RUBY-2741
=> Fix/ruby 2741 pafs om 2 view summary om 2 column e non residential properties summary details missing in UI
