app/models/pafs_core/user.rb, app/models/pafs_core/user_area.rb, db/migrate/20160309103101_create_users.rb, db/migrate/20160602100101_create_user_areas.rb, spec/dummy/db/schema.rb, spec/factories/user_areas.rb, spec/factories/users.rb, spec/models/pafs_core/user_area_spec.rb, spec/models/pafs_core/user_spec.rb
=> moved user model to pafs_core

app/controllers/pafs_core/projects_controller.rb, app/services/pafs_core/project_navigator.rb, app/services/pafs_core/project_service.rb, app/views/pafs_core/projects/funding.html.erb, app/views/pafs_core/projects/new.html.erb, config/locales/en.yml, config/routes.rb, spec/controllers/pafs_core/projects_controller_spec.rb
Added questions for whether the project requires GiA or local levy funding before 31 March 2021 to determine whether project is a pipeline project or not.
=> Added initial questions create project (PK-404, PK-621, PK-403)

app/steps/pafs_core/ready_for_service_date_step.rb, app/views/pafs_core/projects/index.html.erb, app/views/pafs_core/projects/steps/_funding_calculator_upload.html.erb, config/locales/steps.en.yml, lib/pafs_core/project_types.rb, spec/steps/pafs_core/ready_for_service_date_step_spec.rb
PM-140, PM-168, PM-180, PM-199, PM-207, PM-208
=> PM-140, PM-168, PM-180, PM-199, PM-207, PM-208

app/views/pafs_core/projects/steps/approach.html.erb, app/views/pafs_core/projects/steps/urgency_details.html.erb, app/views/shared/_single_numeric_field_form.html.erb
Adding (visually hidden) labels for accessibility conformance
=> Added labels to unlabelled fields (PM-134)

app/views/pafs_core/projects/steps/_funding_calculator_upload.html.erb, app/views/pafs_core/projects/steps/earliest_date.html.erb, app/views/pafs_core/projects/steps/project_name.html.erb, app/views/summary/_urgency.html.erb, config/locales/steps.en.yml
PM-179, PM-221, PM-222, PM-220, PM-178
=> PM-179, PM-221, PM-222, PM-220, PM-178

app/views/shared/_contributors_form.html.erb
Added hidden labels to contributor textarea field for better accessibility
=> Added label to textarea fields (PM-134)

app/views/pafs_core/projects/steps/location.html.erb
=> Added label for location field (PM-132)

app/views/pafs_core/projects/index.html.erb
Re-styling of submission dates
=> pm-176 again

app/views/pafs_core/projects/steps/approach.html.erb, app/views/pafs_core/projects/steps/ready_for_service_date.html.erb, config/locales/steps.en.yml
PM-223, PM-225, PM-230: more text changes.
=> PM-223, PM-225, PM-230

app/views/pafs_core/errors/404.html.erb, config/locales/exceptions.en.yml
Alternative error to make 404 message more applicable to the admin pages
=> Added error change for alternative message

app/views/pafs_core/projects/steps/benefit_area_file.html.erb, app/views/pafs_core/projects/steps/coastal_erosion_protection_outcomes.html.erb, app/views/pafs_core/projects/steps/flood_protection_outcomes.html.erb, app/views/pafs_core/projects/steps/project_name.html.erb, app/views/summary/_key_dates.html.erb, config/locales/steps.en.yml
Added additional labels for better accessibility with screen readers
=> Added missing labels (PM-134)

app/controllers/pafs_core/application_controller.rb, app/models/pafs_core/account_request.rb, app/services/pafs_core/asite_service.rb
Moved sending account request email into front-end, moved emails into ActiveJob background thread.
=> Send account request emails (PM-238)

app/steps/pafs_core/coastal_erosion_protection_outcomes_step.rb, app/steps/pafs_core/flood_protection_outcomes_step.rb, spec/steps/pafs_core/coastal_erosion_protection_outcomes_step_spec.rb, spec/steps/pafs_core/flood_protection_outcomes_step_spec.rb
JIRA-192 number of households less than or equal to 1 million.
=> JIRA-192 number of households less than or equal to 1 million.

Gemfile, Gemfile.lock, db/migrate/20170228113527_create_old_passwords.rb, spec/dummy/db/schema.rb
Strengthening password handling.
=> Added password history table (PM-244)

app/assets/stylesheets/pafs_core/_projects.scss
Set link focus highlight colour on project table for accessibility
=> Fixed link focus highlighting in projects table (PM-129)

app/views/pafs_core/projects/steps/financial_year.html.erb, app/views/pafs_core/projects/steps/standard_of_protection.html.erb, app/views/pafs_core/projects/steps/standard_of_protection_after.html.erb, app/views/pafs_core/projects/steps/standard_of_protection_coastal.html.erb, app/views/pafs_core/projects/steps/standard_of_protection_coastal_after.html.erb
=> Made minor accessibility changes to markup (PM-131)

app/views/summary/_location.html.erb
=> Fixed issue with image link (PM-262)

app/views/pafs_core/projects/steps/earliest_date.html.erb, app/views/pafs_core/projects/steps/ready_for_service_date.html.erb
=> Fixing label issues

app/views/summary/_coastal_erosion_protection_outcomes_detail.html.erb, app/views/summary/_flood_protection_outcomes_detail.html.erb, app/views/summary/_funding_sources.html.erb, app/views/summary/_funding_sources_and_spending_detail.html.erb, app/views/summary/_risks.html.erb, config/locales/summary.en.yml
PM-148 further changes plus now included contributors.
=> PM-148 again

app/assets/stylesheets/pafs_core/_projects.scss, app/views/summary/_funding_sources.html.erb, app/views/summary/_funding_sources_and_spending_detail.html.erb, app/views/summary/_risks.html.erb
Further changes for the details tables.
=> Pm 148 iteration 3

app/assets/stylesheets/pafs_core/_projects.scss, app/presenters/pafs_core/project_summary_presenter.rb, app/views/summary/_coastal_erosion_protection_outcomes_detail.html.erb, app/views/summary/_flood_protection_outcomes_detail.html.erb, app/views/summary/_funding_sources.html.erb, app/views/summary/_risks.html.erb
Pm 148 4th iteration plus all numbers potentially using commas for the thousands separator.
=> Pm 148 4th iteration

app/assets/stylesheets/pafs_core/_projects.scss, app/helpers/pafs_core/application_helper.rb, app/services/pafs_core/project_navigator.rb, app/services/pafs_core/project_service.rb, app/views/pafs_core/projects/index.html.erb
Sorting the three columns that are plain sortable in the database.
=> Pm 169 sorting

app/assets/stylesheets/pafs_core/_projects.scss
Changes to stop overcommit warnings on on the new sortable heading styles.
=> Pm 169 2nd iteration

app/assets/stylesheets/pafs_core/_projects.scss, app/views/summary/_coastal_erosion_protection_outcomes_detail.html.erb, app/views/summary/_flood_protection_outcomes_detail.html.erb
Re-aligning columns for the risk related project overview details tables.
=> Further cosmetics

app/assets/stylesheets/pafs_core/_projects.scss, app/helpers/pafs_core/application_helper.rb, app/views/pafs_core/projects/index.html.erb
Changes to the formatting of the sort on the "my proposals" page.
=> Sort formatting

app/assets/stylesheets/pafs_core/_projects.scss, app/controllers/pafs_core/projects_controller.rb, app/models/pafs_core/project.rb, app/views/pafs_core/projects/index.html.erb
Added "TS" back into the reference_number regex as a valid RFCC code. Fixed layout problem in "Your proposals" page. Removed some commented out methods cruft.
=> Fixed issue with reg_ex and layout

app/views/pafs_core/projects/confirm_area.html.erb, app/views/pafs_core/projects/confirm_pso.html.erb
As APT users now have access and can download/export the wording and instructions need updating for PSO users.
=> Updated text to reflect APT access

app/controllers/pafs_core/downloads_controller.rb, app/controllers/pafs_core/multi_downloads_controller.rb, app/services/pafs_core/program_upload_service.rb, app/services/pafs_core/spreadsheet_service.rb, app/views/pafs_core/multi_downloads/index.html.erb, app/views/pafs_core/projects/index.html.erb, config/routes.rb
Fixing missing formulas and "xx" values in the multi project FCERM1 export.
Also fixed routing issue with downloads_path and incremented the starting row for the spreadsheet importer
=> Fixed multi project FCERM1 export (PM-297) and downloads issue

.travis.yml, app/assets/stylesheets/pafs_core/_projects.scss, app/controllers/pafs_core/multi_downloads_controller.rb, app/jobs/pafs_core/generate_area_programme_job.rb, app/mailers/pafs_core/apt_notification_mailer.rb, app/models/pafs_core/area.rb, app/models/pafs_core/area_download.rb, app/models/pafs_core/user.rb, app/presenters/pafs_core/projects_download_presenter.rb, app/services/pafs_core/area_download_service.rb, app/services/pafs_core/development_file_storage_service.rb, app/services/pafs_core/file_storage_service.rb, app/services/pafs_core/spreadsheet_service.rb, app/views/pafs_core/apt_notification_mailer/area_programme_generation_complete.html.erb, app/views/pafs_core/apt_notification_mailer/area_programme_generation_complete.text.erb, app/views/pafs_core/apt_notification_mailer/area_programme_generation_failed.html.erb, app/views/pafs_core/apt_notification_mailer/area_programme_generation_failed.text.erb, app/views/pafs_core/multi_downloads/_empty.html.erb, app/views/pafs_core/multi_downloads/_failed.html.erb, app/views/pafs_core/multi_downloads/_generating.html.erb, app/views/pafs_core/multi_downloads/_ready.html.erb, app/views/pafs_core/multi_downloads/index.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20170607091048_create_pafs_core_area_downloads.rb, lib/pafs_core/files.rb, spec/dummy/db/schema.rb
Now users have been entering projects, we are seeing performance problems during document generation for area programme. This has now been moved to ActiveJob and the user journey modified as an attempt to remedy this.
=> Moved area programming generation into ActiveJob

app/services/pafs_core/program_upload_service.rb
Added find method to `ProgramUploadService`
=> Added find method for program uploads

app/services/pafs_core/calculator_parser_service.rb
Row number now out by one after previous fix against old version of PF calc.
=> Fix offset for PFCalc OM4 fields

config/locales/pafs_core.en.yml
Add locales for PafsCore::AccountRequest
=> [PK-972] Amend the request account page to include access needed

config/locales/steps.en.yml
=> [PK-884] - Rewrite project types

app/views/summary/_key_dates.html.erb
Update "Important Dates" so that a user is forced to go through each date.
=> [PK-965] Revert important dates

app/steps/pafs_core/coastal_erosion_protection_outcomes_step.rb, app/steps/pafs_core/flood_protection_outcomes_step.rb
values are not set when there are no households to protect.
=> Update validation of flood and coastal erosion protection forms so that

app/models/pafs_core/user_area.rb
https://eaflood.atlassian.net/browse/PK-1049
=> Make sure we order an user area by it's primary setting

app/presenters/pafs_core/spreadsheet_presenter.rb, app/services/pafs_core/project_navigator.rb, app/services/pafs_core/project_service.rb
https://eaflood.atlassian.net/browse/PK-970
Allow users to be able to download all project programmes.
=> [PK-970] area programming staff download draft status projects

app/controllers/pafs_core/archives_controller.rb, app/controllers/pafs_core/projects_controller.rb, app/models/pafs_core/project.rb, app/models/pafs_core/state.rb, app/services/pafs_core/project_navigator.rb, app/services/pafs_core/project_service.rb, app/views/pafs_core/archives/index.html.erb, app/views/pafs_core/projects/_confirm_banner.html.erb, app/views/pafs_core/projects/confirm_archive.html.erb, app/views/pafs_core/projects/index.html.erb, app/views/pafs_core/projects/show.html.erb, app/views/summary/_approach.html.erb, app/views/summary/_earliest_start.html.erb, app/views/summary/_environmental_outcomes.html.erb, app/views/summary/_funding_calculator.html.erb, app/views/summary/_funding_sources.html.erb, app/views/summary/_funding_values.html.erb, app/views/summary/_key_dates.html.erb, app/views/summary/_location.html.erb, app/views/summary/_risks.html.erb, app/views/summary/_standard_of_protection.html.erb, app/views/summary/_urgency.html.erb, config/locales/en.yml, config/locales/titles.en.yml, config/routes.rb, spec/services/pafs_core/project_service_spec.rb
https://eaflood.atlassian.net/browse/PK-1043
=> [PK-1043] Archive proposals for RMA & PSO

app/helpers/pafs_core/projects_helper.rb, app/presenters/pafs_core/spreadsheet_presenter.rb, spec/services/pafs_core/spreadsheet_service_spec.rb
https://eaflood.atlassian.net/browse/PK-1059
=> [PK-1059] fcrm1 status to reflect actual pafs status

Gemfile, Gemfile.lock, app/controllers/pafs_core/multi_downloads_controller.rb
=> [PK-1065] Make sure that proposals with completed are calculated as proposals over

Gemfile.lock
Resolves CVE-2018-1000544
To be merged before https://github.com/DEFRA/pafs_core/pull/207
=> Update rubyzip to resolve [CVE-2018-1000544]

app/views/pafs_core/projects/index.html.erb
Allowing them to sort by area, as requested in https://eaflood.atlassian.net/browse/PK-1070
=> Allow users to sort by "Created By".

app/controllers/pafs_core/projects_controller.rb, app/views/pafs_core/projects/index.html.erb
Resolve sorting issue and allow only PSO users to sort by "Created By" column.
=> Make sure that only PSO users can order by "Created by"

app/controllers/pafs_core/projects_controller.rb, app/views/pafs_core/projects/index.html.erb
As requested, dropping functionality to sort by created by.
=> Remove sort by on created by

app/presenters/pafs_core/camc3_presenter.rb
Initial shell for handling CAMC3 data mapping.
=> Add initial presenter class for managing CACM3 related data mapping.

app/presenters/pafs_core/camc3_presenter.rb, lib/pafs_core.rb, lib/pafs_core/mapper/fcerm.rb, spec/lib/pafs_core/mapper/fcerm_spec.rb, spec/presenters/pafs_core/camc3_presenter_spec.rb
https://eaflood.atlassian.net/browse/PK-1099
Extract FCERM1 OM2 & OM3 data from PAFS, preparing for implementing CAMC3 client.
=> Allow CAMC3 client to extract data from the FCERM1 OM2 & OM3 data sets

app/presenters/pafs_core/partnership_funding_calculator_presenter.rb, lib/pafs_core.rb, lib/pafs_core/mapper/partnership_funding_calculator.rb, spec/lib/pafs_core/mapper/partnership_funding_calculator_spec.rb, spec/presenters/pafs_core/partnership_funding_calculator_presenter_spec.rb
https://eaflood.atlassian.net/browse/PK-1108
Extract Partnership Funding Calculator data from PAFS, so CAMC3 can consume it.
=> Extract PF Calculator data for CAMC3

app/presenters/pafs_core/camc3_presenter.rb, app/presenters/pafs_core/partnership_funding_calculator_presenter.rb, lib/pafs_core/mapper/partnership_funding_calculator.rb, spec/presenters/pafs_core/camc3_presenter_spec.rb
PafsCore::PartnershipFundingCalculatorPresenter into PafsCore::Camc3Presenter so we can test that downloading the file works as expected.
=> Integrate PF Calculator extraction.

app/presenters/pafs_core/camc3_presenter.rb, app/presenters/pafs_core/partnership_funding_calculator_presenter.rb, lib/pafs_core/mapper/fcerm.rb, lib/pafs_core/mapper/partnership_funding_calculator.rb, spec/lib/pafs_core/mapper/fcerm_spec.rb, spec/lib/pafs_core/mapper/partnership_funding_calculator_spec.rb
https://eaflood.atlassian.net/browse/PK-1109
Extract the remaining FCERM1 data from PAFS, so we can send it across to CAMC3.
=> Integrate remaining fcerm1 data extract

app/presenters/pafs_core/camc3_presenter.rb, lib/pafs_core/fcerm1.rb, lib/pafs_core/mapper/fcerm.rb, lib/pafs_core/mapper/partnership_funding_calculator.rb, spec/lib/pafs_core/mapper/partnership_funding_calculator_spec.rb
Update JSON payload for sending across to CAMC3, includes updating outcomes measures.
https://eaflood.atlassian.net/browse/PM-355
=> Update data extraction for CAMC3

app/controllers/pafs_core/projects_controller.rb, app/views/pafs_core/projects/index.html.erb
Pass the sort order and column through to the view
=> [PM-368] Fix for sort direction UI

spec/controllers/pafs_core/projects_controller_spec.rb
Refactor to use `let` rather than variables in controller spec for projects
=> [PM-384] Refactor projects controller spec

app/presenters/pafs_core/camc3_presenter.rb, spec/presenters/pafs_core/camc3_presenter_spec.rb
* Remove Fish or eel Barrier
* OM4e - Should link to - Fish or eel amount
* OMf - Should link to - River Habitat Protected/Imporved
=> [PM-395] Correct OM4 values in JSON output

lib/pafs_core/mapper/partnership_funding_calculator.rb, spec/lib/pafs_core/mapper/partnership_funding_calculator_spec.rb
* Add parsed content of calculator.xlsx H29 to the generated json
=> [PM-396] Add whole life benefits to JSON

app/decorators/pafs_core/imported_project_decorator.rb, app/presenters/pafs_core/camc3_presenter.rb, app/presenters/pafs_core/partnership_funding_calculator_presenter.rb, app/steps/pafs_core/urgency_step.rb, spec/factories/steps.rb, spec/presenters/pafs_core/camc3_presenter_spec.rb, spec/steps/pafs_core/urgency_step_spec.rb
* Adds urgency details to the JSON output for CAMC3
=> [PM-405] Add urgency details to CAMC3 Presenter

lib/pafs_core/mapper/fcerm.rb, spec/factories/projects.rb, spec/lib/pafs_core/mapper/fcerm_spec.rb, spec/presenters/pafs_core/camc3_presenter_spec.rb
* Add `email` attribute to JSON
* Value is the email of the creator of the project
=> [PM-412] Add creator email to JSON

config/locales/spreadsheet.en.yml
The moderation code for emergency works should be 'Emergency', not
'Other'
=> [PM-431] Moderation code Other -> Emergency

Guardfile, app/services/pafs_core/map_service.rb
* Add guardfile for rspec
* Remove noisy logging from Faraday
=> [PM-399] Add guard and reduce Faraday logging

app/helpers/pafs_core/projects_helper.rb, app/views/pafs_core/projects/index.html.erb, app/views/pafs_core/projects/show.html.erb, app/views/summary/_approach.html.erb, app/views/summary/_coastal_erosion_protection_outcomes_detail.html.erb, app/views/summary/_earliest_start.html.erb, app/views/summary/_environmental_outcomes.html.erb, app/views/summary/_financial_year.html.erb, app/views/summary/_funding_calculator.html.erb, app/views/summary/_funding_sources.html.erb, app/views/summary/_funding_values.html.erb, app/views/summary/_key_dates.html.erb, app/views/summary/_location.html.erb, app/views/summary/_project_name.html.erb, app/views/summary/_project_type.html.erb, app/views/summary/_risks.html.erb, app/views/summary/_standard_of_protection.html.erb, app/views/summary/_urgency.html.erb
* PSOs can no longer change project statuses
* PSOs cannot edit sections of a project
* PSOs cannot create new projects
=> [PM-377] Remove PSO project edit and create

app/helpers/pafs_core/projects_helper.rb, app/views/pafs_core/projects/_submit_project.html.erb, app/views/pafs_core/projects/show.html.erb
* Change status edit links for PSOs
* Change submit for PSO's to refer to PoL
=> [PM-437] Change the status buttons to refer PSO users to PoL

spec/controllers/pafs_core/bootstraps_controller_spec.rb, spec/factories/areas.rb, spec/services/pafs_core/project_service_spec.rb
* Corrects factory to produce valid areas
* Refactor specs to use new factories
=> [PM-399] Fix and refactor Area factories

app/helpers/pafs_core/projects_helper.rb, app/models/pafs_core/area.rb, app/models/pafs_core/project.rb, app/views/pafs_core/projects/_submit_project.html.erb, app/views/pafs_core/projects/index.html.erb, app/views/summary/_approach.html.erb, app/views/summary/_earliest_start.html.erb, app/views/summary/_environmental_outcomes.html.erb, app/views/summary/_financial_year.html.erb, app/views/summary/_funding_calculator.html.erb, app/views/summary/_funding_sources.html.erb, app/views/summary/_funding_values.html.erb, app/views/summary/_key_dates.html.erb, app/views/summary/_location.html.erb, app/views/summary/_project_name.html.erb, app/views/summary/_project_type.html.erb, app/views/summary/_risks.html.erb, app/views/summary/_standard_of_protection.html.erb, app/views/summary/_urgency.html.erb
* PSOs can still edit RMA-area projects
* PSO-area projects are affected by the new flag
=> [PM-377] Change PSO restriction to scope to area project is in

config/locales/spreadsheet.en.yml
=> [PM-433] Change Health & Safety -> Health and Safety

Gemfile.lock, lib/pafs_core.rb, lib/pafs_core/pol/azure_oauth.rb, lib/pafs_core/pol/azure_vault_client.rb, pafs_core.gemspec, spec/lib/pafs_core/pol/azure_oauth_spec.rb, spec/lib/pafs_core/pol/azure_vault_client_spec.rb, spec/rails_helper.rb
This is required for the integration with PoL - this allows us to get a secure token used to authenticate the requests.
=> [PM-473] Add Azure vault oauth and secret classes

db/migrate/20190619134726_add_submitted_to_pol_to_pafs_core_projects.rb, lib/pafs_core/pol/submission.rb, spec/dummy/db/schema.rb, spec/lib/pafs_core/pol/submission_spec.rb
* Adds a new column, so migration required
* On successful submission, records the current datetime against the 
project
=> [PM-482] Record datetime of successful submission to PoL

app/models/pafs_core/project.rb, spec/factories/projects.rb
* Add submitted to pol scope to project factory
=> [PM-451] Submission to PoL

lib/pafs_core/rfcc_codes.rb
=> [PM-528] Anglian Central => Anglian Great Ouse

app/controllers/pafs_core/projects_controller.rb, app/views/pafs_core/projects/_submit_project.html.erb
* Removes the need for RMA users to have their projects approved
* Allows direct submission once the PoL integration goes live
=> [PM-529] Remove approval process for RMAs

app/views/pafs_core/projects/index.html.erb
Improvement to the content, as there has been some confusion. The comms
is not reasching to all of the users. So I thought this content would
help a little bit in PAFS.
=> [PM-558] Improve go to AIMS wording for new projects

Gemfile, Gemfile.lock, doc/json_schemas/camc3.json, spec/factories/area_projects.rb, spec/factories/projects.rb, spec/presenters/pafs_core/camc3_presenter_spec.rb, spec/support/matchers/json_schema_matcher.rb
* Schema to verify camc3 payload json
* Integrated into specs
=> [PM-567] Add json schema

app/models/pafs_core/funding_value.rb, app/steps/pafs_core/funding_sources_step.rb, spec/models/pafs_core/funding_value_spec.rb
FV total is not updating unless the funding sources section is run
through to the value update. THis causes incorrect totals to be
displayed if the funding sources change.
=> [PM-580] Fix for funding value total

app/steps/pafs_core/funding_calculator_step.rb, spec/steps/pafs_core/funding_calculator_step_spec.rb
https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-1907
=> Update error message for PF calculator version

app/steps/pafs_core/funding_calculator_step.rb
https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-1907
=> Update error message for v9 PF calculator

app/views/summary/_natural_flood_risk_measures.html.erb
=> add ids to nfm summary section

app/presenters/pafs_core/validation_presenter.rb, spec/presenters/pafs_core/validation_presenter_spec.rb
=> Add validation for natural flood risks section

app/assets/javascripts/pafs_core/other_flood_measures.js, app/presenters/pafs_core/validation_presenter.rb, app/steps/pafs_core/natural_flood_risk_measures_step.rb, app/views/pafs_core/projects/steps/natural_flood_risk_measures.html.erb, app/views/pafs_core/projects/steps/natural_flood_risk_measures_cost.html.erb, app/views/summary/_natural_flood_risk_measures.html.erb, db/migrate/20220606105448_add_other_flood_measure_selected.rb, lib/pafs_core/natural_flood_risk_measures.rb, spec/dummy/db/schema.rb, spec/steps/pafs_core/natural_flood_risk_measures_step_spec.rb
=> Add error message if user does not provide the name of other flood risk measure

app/steps/pafs_core/natural_flood_risk_measures_included_step.rb, app/steps/pafs_core/natural_flood_risk_measures_step.rb, app/views/pafs_core/projects/steps/natural_flood_risk_measures.html.erb, spec/steps/pafs_core/natural_flood_risk_measures_step_spec.rb
=> remove other nfm text value if unselected

app/presenters/pafs_core/camc3_presenter.rb, doc/json_schemas/project.json, spec/presenters/pafs_core/camc3_presenter_spec.rb
Adds the NFM measures to the POL integration
=> Add nfm measures to camc3 presenter

app/steps/pafs_core/kilometres_of_watercourse_enhanced_or_created_comprehensive_step.rb, app/steps/pafs_core/kilometres_of_watercourse_enhanced_or_created_partial_step.rb, app/steps/pafs_core/kilometres_of_watercourse_enhanced_or_created_single_step.rb, config/locales/steps.en.yml, spec/steps/pafs_core/kilometres_of_watercourse_enhanced_or_created_comprehensive_step_spec.rb, spec/steps/pafs_core/kilometres_of_watercourse_enhanced_or_created_partial_step_spec.rb, spec/steps/pafs_core/kilometres_of_watercourse_enhanced_or_created_single_step_spec.rb
https://eaflood.atlassian.net/browse/RUBY-1930?focusedCommentId=418452
Fixes typos and incorrect error messages
=> fix typos in error messages and hint text

app/presenters/pafs_core/camc3_presenter.rb, app/presenters/pafs_core/spreadsheet_presenter.rb, doc/json_schemas/project.json
https://eaflood.atlassian.net/browse/RUBY-1930
Updates OM4a and OM4b attributes sent to POL
=> add separate values for om4a and om4b attributes

app/views/summary/_natural_flood_risk_measures.html.erb
https://eaflood.atlassian.net/browse/RUBY-1920?focusedCommentId=423562
=> change scope of translations on nfm summary

app/assets/stylesheets/pafs_core/_projects.scss, config/locales/steps.en.yml
https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-1958
=> adjust column widths to make columns D & E more visible

app/views/pafs_core/projects/steps/coastal_erosion_protection_outcomes.html.erb, config/locales/summary.en.yml
https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-1959
https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-1960
=> update form labels and summary titles

app/presenters/pafs_core/project_summary_presenter.rb, app/views/summary/_environmental_outcomes.html.erb, spec/presenters/pafs_core/project_summary_presenter_spec.rb
https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-2009
=> add N/A display for environmental benefits

app/assets/stylesheets/pafs_core/_projects.scss, app/views/pafs_core/projects/steps/coastal_erosion_protection_outcomes.html.erb, app/views/pafs_core/projects/steps/flood_protection_outcomes.html.erb, app/views/pafs_core/projects/steps/flood_protection_outcomes2040.html.erb
https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-12068
=> use full page for fpos and ceos

app/assets/stylesheets/pafs_core/_projects.scss, app/views/pafs_core/projects/steps/flood_protection_outcomes.html.erb
https://eaflood.atlassian.net/jira/software/projects/RUBY/boards/374?selectedIssue=RUBY-2068
=> adjust column widths on fpo page

.rubocop.yml, app/services/pafs_core/download/base.rb
https://eaflood.atlassian.net/browse/RUBY-2145
=> Reinstate base download initializer

app/mailers/pafs_core/apt_notification_mailer.rb
https://eaflood.atlassian.net/browse/RUBY-2145
=> Fix add_template_helper issue

app/steps/pafs_core/benefit_area_file_step.rb
https://eaflood.atlassian.net/browse/RUBY-2145
=> Add missing space in prompt

app/views/pafs_core/projects/steps/benefit_area_file.html.erb
https://eaflood.atlassian.net/browse/RUBY-2152
=> Set title for benefit area page

app/assets/stylesheets/pafs_core/_projects.scss, app/helpers/pafs_core/application_helper.rb, app/presenters/pafs_core/validation_presenter.rb, app/views/pafs_core/projects/index.html.erb, app/views/pafs_core/projects/steps/benefit_area_file_summary.html.erb, app/views/pafs_core/projects/steps/funding_values.html.erb, app/views/pafs_core/projects/steps/project_name.html.erb, app/views/pafs_core/projects/steps/standard_of_protection_coastal.html.erb, app/views/pafs_core/projects/steps/standard_of_protection_coastal_after.html.erb, app/views/shared/_contributor_values_form.html.erb, app/views/shared/_contributors_form.html.erb
This change fixes a number of layout issues, primarily around tables.
https://eaflood.atlassian.net/browse/RUBY-2178
=> Fix layout issues

app/assets/stylesheets/pafs_core/_projects.scss, app/views/pafs_core/projects/_confirm_banner.html.erb, app/views/pafs_core/projects/steps/coastal_erosion_protection_outcomes.html.erb, config/locales/en.yml, config/locales/steps.en.yml
This change addresses layout and I18n issues impacting pafs-user.
https://eaflood.atlassian.net/browse/RUBY-2178
=> Further layout changes

app/services/pafs_core/spreadsheet_service.rb
https://eaflood.atlassian.net/browse/RUBY-2369
=> Include exception message in download-all error

app/services/pafs_core/download/all.rb, app/services/pafs_core/spreadsheet_service.rb
https://eaflood.atlassian.net/browse/RUBY-2369
=> Download error logging

app/presenters/pafs_core/spreadsheet_presenter.rb, spec/presenters/pafs_core/spreadsheet_presenter_spec.rb
Add missing spreadsheet presenter methods
https://eaflood.atlassian.net/browse/RUBY-2166
=> Fix download all projects

app/models/pafs_core/funding_value.rb, app/steps/pafs_core/fcrm_gia_funding_sources_step.rb, app/steps/pafs_core/funding_values_step.rb, config/locales/steps.en.yml, lib/pafs_core/funding_sources.rb
- Allow storing funding values for the new fcrm fields
- Add columns for new funding values to funding values page when selected
- Add new funding values to json
Jira ticket: https://eaflood.atlassian.net/browse/RUBY-1965
=> feature/RUBY 1965 PAFS Additional FCRM GIA 2 Add estimated funding spend for each year

app/models/pafs_core/funding_value.rb, app/steps/pafs_core/fcrm_gia_funding_sources_step.rb, app/steps/pafs_core/funding_values_step.rb, config/locales/steps.en.yml, doc/json_schemas/project.json, lib/pafs_core/funding_sources.rb, lib/pafs_core/mapper/funding_sources.rb, spec/lib/pafs_core/mapper/funding_sources_spec.rb
https://eaflood.atlassian.net/browse/RUBY-2430
=> Add the new grant in aid values to the JSON export

app/models/pafs_core/area_download.rb, spec/services/pafs_core/area_download_service_spec.rb
https://eaflood.atlassian.net/browse/RUBY-2409
=> Add FSM state transition to support download regeneration

app/services/pafs_core/change_project_area_service.rb, spec/services/pafs_core/change_project_area_service_spec.rb
https://eaflood.atlassian.net/browse/RUBY-2360
=> Remove old area_project when changing RMA

app/views/pafs_core/projects/steps/funding_values.html.erb
No Jira ticket
https://defra-digital.slack.com/archives/D04SH6ARRFZ/p1681209624783039
old
new
=> Remove govuk-grid-column-three-quarters from table css to increase size of table

app/views/pafs_core/projects/steps/funding_values.html.erb
https://eaflood.atlassian.net/browse/RUBY-2451
=> Fix values table footer cell HTML classes

app/services/pafs_core/download/all.rb
https://eaflood.atlassian.net/browse/RUBY-2479
=> Remove redundant debug statements

db/migrate/20230620214333_add_missing_indexes.rb, spec/dummy/db/schema.rb
https://eaflood.atlassian.net/browse/RUBY-2592
=> RUBY-2400: Adding missing DB indexes

app/models/pafs_core/organisation.rb, db/migrate/20230814115629_create_pafs_core_organisations.rb, spec/dummy/db/schema.rb, spec/factories/organisations.rb, spec/models/pafs_core/organisation_spec.rb
https://eaflood.atlassian.net/browse/RUBY-2444
Organisations 
- DB table
- Model
- Factory
- Specs
=> RUBY-2444: Adding organisations db table + model + specs

app/models/pafs_core/area.rb, lib/pafs_core/data_migration/update_authorities.rb, spec/factories/areas.rb
https://eaflood.atlassian.net/browse/RUBY-2445
- Adding factory for authority
=> RUBY-2445: Adding factory for authority

app/models/pafs_core/area.rb, app/services/pafs_core/area_importer.rb, spec/factories/areas.rb
https://eaflood.atlassian.net/browse/RUBY-2448
=> RUBY-2448: making identifier a rerquired field

lib/pafs_core/fcerm1.rb
https://eaflood.atlassian.net/browse/RUBY-2991
=> [RUBY-2991] fixing typo in column name

app/presenters/pafs_core/project_summary_presenter.rb, app/presenters/pafs_core/validation_presenter.rb, lib/pafs_core/project_types.rb, spec/presenters/pafs_core/project_summary_presenter_spec.rb, spec/presenters/pafs_core/validation_presenter_spec.rb
Remove the requirement to upload PFC for certain project types
https://eaflood.atlassian.net/browse/RUBY-3142
=> [RUBY-3142] make PFC requirement optional for some project types

app/steps/pafs_core/carbon_cost_operation_step.rb, app/views/pafs_core/projects/steps/carbon_cost_operation.html.erb, config/locales/en.yml, config/locales/steps.en.yml, spec/factories/steps.rb, spec/steps/pafs_core/carbon_cost_operation_step_spec.rb
PAFS - Carbon Net Zero - 3 - Operational carbon page
https://eaflood.atlassian.net/browse/RUBY-3922
=> RUBY-3922: Adjustments to Operational carbon page + specs added

app/controllers/pafs_core/projects_controller.rb, app/views/pafs_core/summary/_carbon.html.erb, config/locales/summary.en.yml
PAFS - Carbon Net Zero - Carbon impact section update
https://eaflood.atlassian.net/browse/RUBY-3852
=> [RUBY-3852] Enhance carbon impact summary section to include all carbon fields and calculations
